apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "deliverybot.dev/secret-checksum": {{ toJson .Values.secrets | sha256sum }}
  labels:
    app: borderless
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "app.matchLabels" . | indent 6 }}
  template:
    metadata:
      annotations:
        akeyless/enabled: "true"
      labels:
        app: borderless
{{ include "app.matchLabels" . | indent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}    
          command:
            - "echo $AKEYLESS_ACCESS_ID"
        {{ with .Values.env }}
          env:
           {{- toYaml . | nindent 12 }}
          #- name: AKEYLESS_ACCESS_ID
          #  value: "akeyless:/cd_production/AKEYLESS_ACCESS_ID"
          #- name: AKEYLESS_ACCESS_KEY
          #  value: "akeyless:/cd_production/AKEYLESS_ACCESS_KEY"
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          {{ with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end -}}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end -}}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
